// DO NOT EDIT THIS FILE
enableSaving [false,false];
setGroupIconsVisible [true,false]; //Show only 2D
enableCamShake true;
setViewDistance 2000;
setTerrainGrid 25;

// clients
if (!isDedicated) then {

	[] spawn {
		waitUntil {!isNull player};
		// deletes grenades thrown in spawn
		player addEventHandler ["Fired",
		{
			if (_this select 2 == "HandGrenadeMuzzle") then
			{
				if ((_this select 0) distance (markerPos (["respawn_west","respawn_east","respawn_guerrila","respawn_civilian"] select ([WEST,EAST,independent,civilian] find side player))) < 50) then
				{
					deleteVehicle (_this select 6);
					titleText ["G IS FOR GRENADES", "PLAIN", 3];
				};
			};
		}];
		sleep  0.3;
		// lower weapon
		player switchMove "amovpercmstpslowwrfldnon";

		// so player never joins "ENEMY" side.
		player addEventHandler ["HandleRating", {
			_rating = _this select 1;
			(abs _rating)
		}];

		// respawn with correct loadout if using template loadout
		_timeOut = time + 15;
		waitUntil {(player getVariable ["FP_kit_type", ""] != "") || time > _timeOut};
		FP_kit_type = player getVariable ["FP_kit_type", ""];

	};
};

// server
if (isServer) then 
{
	createCenter west;
	createCenter east;
	createCenter resistance;
	createCenter civilian;
};